name: "Deploy Cloud Functions to GCP"

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.PROJECT_REGION }}
  RUNTIME: python312
  # CLOUD_RUN_JOB_NAME: ${{ secrets.CLOUD_RUN_JOB_NAME }}
  # CLOUD_RUN_CONTAINER_NAME: ${{ secrets.CLOUD_RUN_CONTAINER_NAME }}
  # FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}

jobs:
  deploy-watch-refresh:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # actions/checkout@v4

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2" # google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: "${{ env.PROJECT_ID }}"

      - name: "Install uv"
        run: |
          pip install uv

      - name: "Generate requirements.txt from uv.lock"
        run: |
          uv sync -n
          uv pip freeze > requirements.txt
          cp requirements.txt src/cloud_functions/gmail_bills_and_statements_message_watcher/requirements.txt

      - name: "Deploy Cloud Function"
        run: |-
          gcloud functions deploy gmail-bills-and-statements-message-watcher \
            --project=$PROJECT_ID \
            --region=$REGION \
            --runtime=$RUNTIME \
            --trigger-http  \
            --no-allow-unauthenticated \
            --source=src/cloud_functions/gmail_bills_and_statements_message_watcher
            --entry-point="refresh_watch" \