name: "Deploy Cloud Functions to GCP"

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.PROJECT_REGION }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  CLOUD_RUN_JOB_NAME: ${{ secrets.CLOUD_RUN_JOB_NAME }}
  CLOUD_RUN_CONTAINER_NAME: ${{ secrets.CLOUD_RUN_CONTAINER_NAME }}
  FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}
  RUNTIME: python312

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # actions/checkout@v4

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2" # google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: "${{ env.PROJECT_ID }}"

      - name: Deploy Cloud Function
        run: |-
          gcloud functions deploy $FUNCTION_NAME \
            --project=$PROJECT_ID \
            --region=$REGION \
            --runtime=$RUNTIME \
            --trigger-bucket=$BUCKET_NAME \
            --entry-point="trigger_dbt_run" \
            --source=./ \